import 'angular-ui-router';
import 'angular-resource'
import 'ui-bootstrap'
import 'ui-bootstrap-js';
import 'ui-bootstrap-tpls-js'
import 'angular-busy-js';
import 'angular-messages';
import 'angular-translate';
import 'angular-static-loader';
import 'angular-simple-logger';
import 'angular-google-maps';
import 'angular-animate';
import 'angular-aria';
import 'angular-messages';
import 'angular-material';
import 'angular-file-upload';
import 'angular-moment';
import 'angular-permission';
import 'angular-permission-ui';
import 'ng-crop-img';
import './resources/';